name: flexwallet2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_analytics: ^10.7.4

  # State Management & Navigation
  get: ^4.6.6
  get_storage: ^2.1.1
  provider: ^6.1.1
  go_router: ^14.6.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6

  # Utils
  intl: ^0.18.1
  uuid: ^4.2.2
  connectivity_plus: ^6.1.0
  flutter_local_notifications: ^18.0.1

  # Auth providers
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.4
  font_awesome_flutter: ^10.7.0

  # Contacts
  flutter_contacts: ^1.1.7

  # Additional dependencies
  badges: ^3.1.2
  shimmer: ^3.0.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/google.png

