// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtcrTWkcMIt-OpztSESRIMWHZayBmnXcs',
    appId: '1:213180313712:web:a393ccaed308cbd63b44b5',
    messagingSenderId: '213180313712',
    projectId: 'flex-wallet',
    authDomain: 'flex-wallet.firebaseapp.com',
    storageBucket: 'flex-wallet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD6T5WWZXmJA3-7YyP6wU3SnKcpSERFWc',
    appId: '1:213180313712:android:785200bdbe8dd48a3b44b5',
    messagingSenderId: '213180313712',
    projectId: 'flex-wallet',
    storageBucket: 'flex-wallet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4YdIWMkUhTdWO29NZHlsZxoXtN9-vMsQ',
    appId: '1:213180313712:ios:9acd404892efe96d3b44b5',
    messagingSenderId: '213180313712',
    projectId: 'flex-wallet',
    storageBucket: 'flex-wallet.firebasestorage.app',
    iosBundleId: 'FlexWallet.flexWalletGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4YdIWMkUhTdWO29NZHlsZxoXtN9-vMsQ',
    appId: '1:213180313712:ios:9acd404892efe96d3b44b5',
    messagingSenderId: '213180313712',
    projectId: 'flex-wallet',
    storageBucket: 'flex-wallet.firebasestorage.app',
    iosBundleId: 'FlexWallet.flexWalletGet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtcrTWkcMIt-OpztSESRIMWHZayBmnXcs',
    appId: '1:213180313712:web:244022c6dee5123c3b44b5',
    messagingSenderId: '213180313712',
    projectId: 'flex-wallet',
    authDomain: 'flex-wallet.firebaseapp.com',
    storageBucket: 'flex-wallet.firebasestorage.app',
  );

}